<?php

namespace Lebed\VideoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository963..
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{

}