lebed_video_homepage:
    pattern:  /
    defaults: { _controller: LebedVideoBundle:Default:index }
lebed_video_videos_of_category:
    pattern: /category/{id}
    defaults: { _controller: LebedVideoBundle:Default:videosOfCategory}

